version: 5.1.0
variant: default
logo: ./img/logo.svg
head:
    favicon: ./img/favicon.ico
    open_graph:
        title:
        type:
        url:
        image:
        site_name:
        author:
        description:
        twitter_card:
        twitter_id:
        twitter_site:
        google_plus:
        fb_admins:
        fb_app_id:
    structured_data:
        title:
        description:
        url:
        author:
        image:
    meta:
        - ''
    rss:
navbar:
    menu:
        Home: /
        Archives: /archives
        Tags: /tags
        About: /about
    links:
        My GitHub:
            icon: fab fa-github
            url: https://github.com/BolasLien
        My Portfolio:
            icon: fas fa-book
            url: https://bolaslien.github.io/
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
search:
    type: insight
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Bolas Lien
        author_title: Frontend Developer
        location: Taipei, Taiwan
        avatar: ./img/avatar.png
        avatar_rounded: false
        gravatar:
        follow_link: https://github.com/BolasLien
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/BolasLien
            Facebook:
                icon: fab fa-facebook
                url: https://www.facebook.com/LChen08
            Linkedin:
                icon: fab fa-linkedin
                url: https://www.linkedin.com/in/bolaslien/
            Mail:
                icon: fas fa-envelope-square
                url: mailto:bolaslien@gmail.com
    -
        position: left
        type: toc
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
plugins:
    animejs: false
    back_to_top: true
    baidu_analytics:
        tracking_id:
    busuanzi: false
    cnzz:
        id:
        web_id:
    gallery: true
    google_analytics:
        tracking_id: G-SG50KRG586
    hotjar:
        site_id:
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
